# Generated by Django 3.2.22 on 2023-10-28 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('website', models.URLField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('featured', models.BooleanField()),
                ('progress', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cotm_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charityApp.charity')),
            ],
        ),
        migrations.CreateModel(
            name='User_History',
            fields=[
                ('historyID', models.AutoField(primary_key=True, serialize=False)),
                ('communityName', models.CharField(max_length=255)),
                ('charityName', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityApp.community')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Community_History',
            fields=[
                ('historyID', models.AutoField(primary_key=True, serialize=False)),
                ('charityName', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('communityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityApp.community')),
            ],
        ),
        migrations.CreateModel(
            name='Community_Comment',
            fields=[
                ('commentID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('communityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityApp.community')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Community_Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityApp.charity')),
                ('communityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityApp.community')),
            ],
        ),
    ]
